describe('Launch Page', function() {
  it('Loads first page with content', function() {
    
    cy.visit(Cypress.env('host'))
    cy.contains('Wrapper tags not typically required')

    cy.get('a').contains('Modernize with Vue 3').click()
    cy.url()
      .should('include', '/mwv3')
      
    cy.get('a').contains('Route Smart').click()
    cy.url()
      .should('include', '/mwv3/router')
    cy.contains('npm install')

    cy.get('a').contains('DevStack (next)').click()
    cy.url()
      .should('include', '/mwv3/devstack')
    
    cy.get('button').contains('>>').click()
    cy.contains('my_frontend')
    cy.get('button').contains('>>').click()
    cy.contains('compose up')
    cy.get('button').contains('>>').click()
    cy.contains('exec -it')
    cy.get('button').contains('>>').click()
    cy.contains('@vitejs')
    cy.get('a').contains('Node Dev (next)').click()
    cy.url()
      .should('include', '/mwv3/vite')
    
    cy.get('a').contains('TypeScript (next)').click()
    cy.url()
      .should('include', '/mwv3/typescript')
    cy.wait(1000)
    cy.get('button').contains('>>').click()
    cy.contains('Works Better')
    cy.get('button').contains('>>').click()
    cy.contains('More hints')
    cy.get('button').contains('>>').click()
    cy.contains('Converts')
    cy.get('button').contains('>>').click()
    cy.contains('Tooling')
    cy.get('button').contains('>>').click()
    cy.contains('Cage Fight')
    
    cy.get('a').contains('Vue Component Scripting (next)').click()
    cy.url()
      .should('include', '/mwv3/compose')
      cy.wait(1000)
      cy.get('button').contains('>>').click()
      cy.contains('composition API style')
      cy.get('button').contains('>>').click()
      cy.contains('Greeting: Hello!!')
      cy.contains('Count: 0')
      cy.contains('Tripple: 0')
      cy.wait(2000)
      cy.get('input[placeholder="Update Count"')
        .type('{selectall}33')
      cy.contains('Count: 33')
      cy.contains('Tripple: 99')
      cy.wait(2000)
      cy.get('input[placeholder="Update Message"')
        .type('{selectall}Bob')
      cy.contains('Greeting: Bob')
      cy.get('button').contains('>>').click()
      cy.contains('options API style')

      cy.get('a').contains('Browser Dev Tools (next)').click()
      cy.url()
        .should('include', '/mwv3/devtools')

      cy.get('a').contains('VSCode Vue Experience (next)').click()
      cy.url()
        .should('include', '/mwv3/volar')

      cy.get('a').contains('Environment Configuration (next)').click()
      cy.url()
        .should('include', '/mwv3/envvar')

      cy.get('a').contains('Global Data State (next)').click()
      cy.url()
        .should('include', '/mwv3/pinia')
  })
})